name: main-workflow

env: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Run all unit tests.
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # Check on the pull request's source code.
      - name: Check out source code
      - uses: actions/checkout@v2
      
      # Install Go.
      - name: Set up Go
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14" # The Go version to download and use.
      - name: Print Go version
        run: go version
      
      # Run unit tests.
      - name: Run unit tests
        run: go test -v ./...